### ISSUE TITLE
Table prefix not working correctly

### ISSUE THREAD

**Issue by kanzelsberger** [Zasilkovna/magento2#2]
My Magento installation is using table prefix in MySQL. When I want to checkout using selected Zasielkovna pickup-point, it fails with following error:

![Screenshot 2020-04-17 at 10 02 01](https://user-images.githubusercontent.com/14909127/79546680-1e974780-8093-11ea-8388-255f8d2e6acf.png)

It wants to insert something to table packetery_order, however my table with prefix is called ts_packetery_order

**Comment by GitHubjbi** [comment]
th same situation
like in post from kanzelsberger

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smartled_toner20.packetery_order' doesn't exist, query was: INSERT INTO packetery_order
					(`order_number`, `recipient_firstname`, `recipient_lastname`, `recipient_phone`, `recipient_company`, `recipient_email`, `cod` ,`currency`,`value`, `weight`,`point_id`,`point_name`,`recipient_street`,`recipient_house_number`,`recipient_city`,`recipient_zip`, `sender_label`, `exported`)
					VALUES (:order_number, :recipient_firstname, :recipient_lastname, :recipient_phone, :recipient_company,:recipient_email, :cod, :currency, :value, :weight, :point_id, :point_name, :recipient_street, :recipient_house_number, :recipient_city, :recipient_zip, :sender_label, :exported) {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smartled_toner20.packetery_order' doesn't exist, query was: INSERT INTO packetery_order
\t\t\t\t\t(`order_number`, `recipient_firstname`, `recipient_lastname`, `recipient_phone`, `recipient_company`, `recipient_email`, `cod` ,`currency`,`value`, `weight`,`point_id`,`point_name`,`recipient_street`,`recipient_house_number`,`recipient_city`,`recipient_zip`, `sender_label`, `exported`)
\t\t\t\t\tVALUES (:order_number, :recipient_firstname, :recipient_lastname, :recipient_phone, :recipient_company,:recipient_email, :cod, :currency, :value, :weight, :point_id, :point_name, :recipient_street, :recipient_house_number, :recipient_city, :recipient_zip, :sender_label, :exported) at /home/smartled/public_html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smartled_toner20.packetery_order' doesn't exist at /home/smartled/public_html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

**Comment by GitHubjbi** [comment]
> My Magento installation is using table prefix in MySQL. When I want to checkout using selected Zasielkovna pickup-point, it fails with following error:
> 
> ![Screenshot 2020-04-17 at 10 02 01](https://user-images.githubusercontent.com/14909127/79546680-1e974780-8093-11ea-8388-255f8d2e6acf.png)
> 
> It wants to insert something to table packetery_order, however my table with prefix is called ts_packetery_order

i have the sam problem like you
