### ISSUE TITLE
Type Error occurred when creating object: Packetery\Checkout\Model\Carrier\Imp\Packetery\Brain, Too few arguments to function

### ISSUE THREAD

**Issue by bhaveshpp** [Zasilkovna/magento2#39]
### I found one issue when  run setup:upgrade on production mode

> https://prnt.sc/1s10q1b

```bash
In AbstractFactory.php line 131:

  Type Error occurred when creating object: Packetery\Checkout\Model\Carrier\Imp\Packetery\Brain, Too few arguments to function Packetery\Checkout
  \Model\Carrier\Imp\Packetery\Brain::__construct(), 5 passed in /web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 1
  21 and exactly 6 expected
```
the module is working fine but only displays this error when run the command in bash.

**Comment by FJiskra** [comment]
What Magento version are you running? Only Magento 2.3 and 2.4 is supported. What module version are you using?

Try this command before running `setup:upgrade`:

`rm -rf generated/code/Packetery`

Also make sure you have correct filesystem permissions set. 

Other option that comes to mind is running commands with `sudo`. After running commands with sudo, you have to fix permissions in magento folder. Browser will likely display error 500, if you do not fix permissions.

**Comment by Skwecode** [comment]
I'm also having this issue, i'm running Magento version 2.4.2, I don't want to run commands with sudo. Does your module only support version 2.4.0?
