### ISSUE TITLE
Transactional email

### ISSUE THREAD

**Issue by Rohaty** [Zasilkovna/magento2#42]
Dobrý deň,
je možné v rozšírení vytvoriť premennú (názov s adresou výdajného miesta), ktorá by sa dala použiť do transakčného emailu, kde by bol  uvedený názov výdajného miesta a jeho adresa?

**Comment by packeta** [comment]
Dobrý den, 
vydali jsme verzi 2.2.2 (https://github.com/Zasilkovna/magento2/releases/tag/v2.2.2) , která přináší proměnné s názvem dopravce nebo výdejního místa.  Návod na použití najdete v readme.md
