### ISSUE TITLE
slovenský preklad

### ISSUE THREAD

**Issue by peter-k77** [Zasilkovna/magento2#56]
Dobrý deň,
Bolo by prosím možné doplniť slovenský preklad?
V prílohe posielam môj preklad, ktorý tam môžete nahrať.
[sk_SK.csv](https://github.com/Zasilkovna/magento2/files/8102992/sk_SK.csv)
Ďakujem,
Peter

**Comment by packeta** [comment]
Dobrý den, 
překlad zkontrolujeme a pokud bude v pořádku,  zařadíme ho do další verze modulu.
